[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; Monitor Serial Speed
monitor_speed = 115200

; Libraries
lib_deps =
    knolleary/PubSubClient @ ^2.8
    ; ArduinoOTA is built-in for ESP32 arduino core, strictly speaking doesn't need lib_deps but good to have explicit context if needed. 
    ; It's core, so usually no need to list it, but we will ensure it's available.

; Upload Protocol (Start with Serial, then switch to espota)
upload_protocol = esptool
; upload_protocol = espota
; upload_port = 192.168.254.XXX ; Un-comment and set IP after first flash
